### ISSUE TITLE
It doesn't work with rails 4

### ISSUE THREAD

**Issue by boogiebpg** [johnantoni/backbone-queryparams-rails#2]
It doesn't work with rails 4, it has railties 3.1 dependency.

**Comment by aguynamedben** [comment]
I noticed this too. It's because @johnantoni merged #1 but didn't create another release. The workaround for now is to specify the git repo and sha1 in your Gemfile

```
gem 'backbone-queryparams-rails', git: 'https://github.com/johnantoni/backbone-queryparams-rails.git', ref: 'a4fae9b24fcaaa45071750a70ddb3ad5d8b172ce'
```

**Comment by johnantoni** [comment]
Thanks for the nudge.

Updated and published to rubygems.org

Apologies for the wait.

**Comment by aguynamedben** [comment]
:+1: cool, thanks for spending time on this @johnantoni!

**Comment by johnantoni** [comment]
no worries
